### ISSUE TITLE
Lucene driver

### ISSUE THREAD

**Issue by jdeolive** [jeo/jeo-contrib#2]
The Lucene library has added some impressive spatial capabilities in recent versions. Having a driver for it could provide a nice embedded on disk format.

**Comment by jericks** [comment]
Awesome!  I can't wait to try this out!

**Comment by jdeolive** [comment]
Thanks Jared! Some feedback would be awesome! Just a word of caution that it is still pretty rough around the edges. I haven't tried it on any "real data" yet,  other than the one that is hand crafted in the vector api test case. But that seems to work ok. It passes all of the vector api tests at least :)
