### ISSUE TITLE
Not found spatial4j version 0.5-VG3

### ISSUE THREAD

**Issue by jimbok8** [jeo/jeo-contrib#3]
There seems to be a problem finding spatial4j version 0.5-VG3, as specified in the solr pom.xml

```
  <properties>
    <solr.version>5.0.0</solr.version>
    <spatial4j.version>0.5-VG3</spatial4j.version>
  </properties>
```

This error was produced
[ERROR] Failed to execute goal on project jeo-solr: Could not resolve dependencies
for project io.jeo:jeo-solr:jar:0-SNAPSHOT: Failure to find com.spatial4j:spatial4j:jar:0.5-VG3
in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository,
resolution will not be reattempted until the
update interval of ossrh has elapsed or updates are forced

**Comment by jdeolive** [comment]
Ahhh, right, need to fix this. Problem is there is not a newer spatial4j artifact past 0.4.1 and the solr module depends on stuff has been added more recently. I'll reach out to the spatial4j team and see about getting a newer artifact in maven central. 

As a workaround for now though here is the maven artifact you can dump into your local maven repo:

  https://dl.dropboxusercontent.com/u/1663985/spatial4j-0.5-VG3.zip
