### ISSUE TITLE
jeo-guava's parent is pointing to util instead of contrib

### ISSUE THREAD

**Issue by ironjan** [jeo/jeo-contrib#6]
Except for jeo-guava, all contrib modules point to contrib as parent:
```
  <parent>
    <groupId>io.jeo</groupId>
    <artifactId>contrib</artifactId>
    <version>0-SNAPSHOT</version>
  </parent>
```

jeo-guava instead points to [util](https://github.com/jeo/jeo/tree/master/util) in the main repository:
```
  <parent>
    <groupId>io.jeo</groupId>
    <artifactId>util</artifactId>
    <version>0-SNAPSHOT</version>
    <relativePath>../../util/</relativePath>
  </parent>
```

Is this expected or should this also be pointing to contrib?

**Comment by jdeolive** [comment]
Yeah, this must have been an oversight, thanks for the fix!
